name: Java Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Đã sửa tên từ action/checkout thành actions/checkout

      - name: Set up JDK
        uses: actions/setup-java@v3  # Đã sửa tên từ action/setup-java thành actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test on windows
        run: mvn clean verify
